### ISSUE TITLE
options.ClientId options.ClientSecret 配置信息我要在程序运行过程中赋值能实再吗？

### ISSUE THREAD

**Issue by qibucloud** [jxnkwlp/AspNetCore.AuthenticationQQ-WebChat#2]
services.AddAuthentication() 
        .AddWeixinAuthentication(options =>
        {
            options.ClientId = "[you app id]";
            options.ClientSecret = "[you app secret]";
        });
options.ClientId options.ClientSecret 配置信息我要在程序运行过程中赋值能实再吗？
我试了好多方法行不通，我不知道怎么弄，能帮我想想吗？

**Comment by jxnkwlp** [comment]
还没遇到过这个场景，   由于 ClientId 从开始到结束都会用到 在 `WeixinAuthenticationHandler  ` 中，  想了下， 可以尝试修改默认的 OAuth 配置 来生成不同的 handler   `builder.AddOAuth<WeixinAuthenticationOptions, WeixinAuthenticationHandler>(authenticationScheme, displayName, configureOptions);`

**Comment by qibucloud** [comment]
@jxnkwlp 还是不是很明白，我不会弄，能简单帮我演示一下吗？

**Comment by jxnkwlp** [comment]
@qibucloud  能描述下你的这个场景吗？   没太理解这个场景是怎么发生的。

**Comment by qibucloud** [comment]
@jxnkwlp 我在做一个多站点的系统，我想做到不同的站点配置不一样的 ClientId ClientSecret 信息

**Comment by jxnkwlp** [comment]
好的，大致明白了，让我想一下 该如何实现 ~

**Comment by viewtance** [comment]
这个有办法改进吗？能动态的读取这个配置的值

**Comment by jxnkwlp** [comment]
@viewtance    @qibucloud     
我的一种实现，查看分支 [muti-site](https://github.com/jxnkwlp/AspNetCore.AuthenticationQQ-WebChat/tree/muti-site/netcore2.0)  ，  已封装到 Microsoft.AspNetCore.Authentication.MultiOAuth 中， 目前对 微信 已实现 。

**Comment by viewtance** [comment]
@jxnkwlp 很不错，有没有企业微信的封装？

**Comment by jxnkwlp** [comment]
@viewtance   暂时还没有哈 ~~ 😅   

我这边目前还没有用到企业微信，如果有了封装代码，一时间也测试不了  😁
